DROP TABLE IF EXISTS patient;

CREATE TABLE patient (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 IMIE VARCHAR(250),
 NAZWISKO VARCHAR(250),
 MIEJSCOWOSC VARCHAR(250),
 KOD VARCHAR(250),
 ULICA VARCHAR(250),
 PESEL VARCHAR(250),
 DATA_URODZENIA VARCHAR(250),
 MAIL VARCHAR(250),
 NR_TELEFONU VARCHAR(250),
 PLEC VARCHAR(250)
);

INSERT INTO patient (IMIE,NAZWISKO,MIEJSCOWOSC,KOD,ULICA,PESEL,DATA_URODZENIA,MAIL,NR_TELEFONU,PLEC) VALUES
    ('Ala', 'Makota','Rzeszow','Kod','Ulica','Pesel','1998-08-22','Mail','Telfeon','Plec'),
    ('Ala3', 'Makota','Rzeszow3','Kod3','Ulica','Pesel','1998-08-22','Mail','Telfeon','Plec'),
    ('Ala2', 'Makota2','Rzeszow2','Kod2','Ulica','Pesel','2000-08-22','Mail','Telfeon','Plec');